services:
  app:
    image: php:8.2-fpm
    container_name: list_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - app-network
    build:
      dockerfile: DockerfilePHP

  nginx:
    image: nginx:alpine
    container_name: list_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mariadb:latest
    container_name: list_db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: list_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
      # PMA_USER: root
      # PMA_PASSWORD: secret
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: list_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
